name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout the repo source code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: 
            python -m pip install .
      - name: Install dev dependencies
        run: |
            python -m pip install -r requirements-dev.txt
            python -m pip install flake8
      - name: Lint with flake8
        run: 
            python -m flake8
      - name: Test with pytest
        run: 
            python -m pytest -m "not cmdtest" 

